Token: <TOKEN>
Use Reactions: True
Recognition Threshold: 0.2
Minimum Word Length: 2
Minimum Emotes: 2
Maximum Emotes: 5
Aliases:
  day: sunrise
  test: newspaper
  math: heavy_plus_sign
  black: black_circle
  blue: blue_circle
  brown: brown_circle
  green: green_circle
  orange: orange_circle
  purple: purple_circle
  red: red_circle
  white: white_circle
  yellow: yellow_circle